#pragma once
namespace OBJECT
{
	enum ID { TILE, EFFECT, BLOCK, BUBBLE, ITEM, PLAYER,COMPLAYER, MONSTER, UI, BUTTON, MOUSE, OBJECT_END };
	enum RENDER_LIST { BACKGROUND, UNDER_EFFECT, RENDER_UI, GAMEOBJECT, POP_UP, POP_UP_BUTTON, RENDER_MOUSE, RENDER_END };
}

namespace BLOCK_TYPE
{
	enum TYPE { EMPTY, NORMAL, BLOCK, BOX, BUSH, BLOCK_END};
}

namespace ITEM_TYPE
{
	enum TYPE { BUBBLE_UP, SPEED_UP, POWER_UP, POWER_MAX, RED_DEVIL, KICK , NEEDLE,ITEM_END };
}


namespace DIRECTION
{
	enum DIREC { UP=0, DOWN=1, LEFT=2, RIGHT=3 , NO_DIREC};
}


namespace KEY_STATE
{
	enum 
	{
		UP = 1, DOWN = 2, RELEASED = 4, PRESSED = 8
	};
}